/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provis9.prak1;

import javax.swing.JOptionPane;

/**
 *
 * @author Josep
 */
public class Futama extends javax.swing.JFrame {

    /**
     * Creates new form Futama
     */
    public Futama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LABEL_NAMA = new javax.swing.JLabel();
        ButtonDuar = new javax.swing.JButton();
        LABEL_KELAS = new javax.swing.JLabel();
        LABEL_NIM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemrograman Provis");

        LABEL_NAMA.setText("Nama : XXXXXX");

        ButtonDuar.setText("RUBAH");
        ButtonDuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDuarMouseClicked(evt);
            }
        });
        ButtonDuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDuarActionPerformed(evt);
            }
        });

        LABEL_KELAS.setText("Kelas : XXXXXX");

        LABEL_NIM.setText("NIM : XXXXXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABEL_KELAS)
                    .addComponent(ButtonDuar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LABEL_NIM)
                    .addComponent(LABEL_NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(LABEL_NAMA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LABEL_KELAS)
                .addGap(18, 18, 18)
                .addComponent(LABEL_NIM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonDuar)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDuarActionPerformed

    private void ButtonDuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDuarMouseClicked
        // TODO add your handling code here:
        LABEL_NAMA.setText("Nama : Josep Victor Rajadoli");
        LABEL_KELAS.setText("Kelas : IF-9");
        LABEL_NIM.setText("NIM : 10118369");
        JOptionPane.showMessageDialog(null, "Selamat, berhasil di rubah asikkk");
    }//GEN-LAST:event_ButtonDuarMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDuar;
    private javax.swing.JLabel LABEL_KELAS;
    private javax.swing.JLabel LABEL_NAMA;
    private javax.swing.JLabel LABEL_NIM;
    // End of variables declaration//GEN-END:variables
}
